config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    get 'users/sign_out', to: 'devise/sessions#destroy'
  end
  devise_for :users, controllers: { sessions: 'users/sessions' }
  get '/admin', to: 'movies#edit', as: 'user_root'
  get '/movies/:id', to: 'movies#rate', as: 'movies_rate'
  post '/movies/:movie_id/comments', to: 'comments#create'
  delete '/movies/:movie_id/comments/:id', to: 'comments#destroy'
  get '/movies/:movie_id/comments', to: 'comments#index', as: 'movie_comments'
  get '/movies_update/:id', to: 'movies#show_update', as: 'movie'
  patch '/movies_update/:id', to: 'movies#update'
  put '/movies_update/:id', to: 'movies#update'
  delete '/movies_edit/:id', to: 'movies#destroy'
  get '/movies_new', to: 'movies#new', as: 'movies_new'
  post '/movies_new', to: 'movies#create', as: 'movies'
  delete '/movies_update/:id', to: 'movies#destroy'

  root 'movies#show'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :movie
  validates :commenter, presence: true
  validates :body, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
    has_many :comments
end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :movie
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  protect_from_forgery prepend: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		@movie = Movie.find(params[:movie_id])
		@comment = @movie.comments.create(comment_params)
		redirect_to movies_rate_path(@movie)
	end
	def destroy
    @movie = Movie.find(params[:movie_id])
    @comment = @movie.comments.find(params[:id])
    @comment.destroy
    redirect_to movies_rate_path(@movie)
	end
     
	private
		def comment_params
			params.require(:comment).permit(:commenter, :body)
		end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def show
		@movies=Movie.all
		@movies=@movies.sort_by{|a| a.title}
	end

	def new
    @movie = Movie.new
  end

	def create
    @movie = Movie.create(movie_params)
    redirect_to user_root_path
  end
	
	def edit
		@movies=Movie.all
		@movies=@movies.sort_by{|a| a.title}
	end

	def show_update
		@movie = Movie.find(params[:id])
	end

	def update
    @movie = Movie.find(params[:id])
    if @movie.update(movie_params)
      redirect_to @movie
    else
      render 'show_update'
    end
  end

	def rate
		@movie= Movie.find(params[:id])
		puts(@movie)
	end

	def destroy
		@movie=Movie.find(params[:id])
    @movie.destroy
    redirect_to user_root_path
  end
	 
  private
    def movie_params
      params.require(:movie).permit(:title, :year, :category)
    end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  #before_action :configure_sign_in_params, only: [:create]
  prepend_before_action :verify_signed_out_user, only: :destroy
  prepend_before_action(only: [:create, :destroy]) { request.env["devise.skip_timeout"] = true }
  # GET /resource/sign_in
  def new
    super
  end

  # POST /resource/sign_in
  def create
    super
  end

  # DELETE /resource/sign_out
  def destroy
    signed_out = (Devise.sign_out_all_scopes ? sign_out : sign_out(user))
    set_flash_message! :notice, :signed_out if signed_out
    yield if block_given?
    respond_to_on_destroy
  end

  def respond_to_on_destroy
    # We actually need to hardcode this as Rails default responder doesn't
    # support returning empty response on GET request
    respond_to do |format|
      format.all { head :no_content }
      format.any(root_path) { redirect_to after_sign_out_path_for(user) }
    end
  end
  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>FilmReview</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

app/views/movies/edit.html.erb
<nav class="navbar navbar-dark bg-dark justify-content-between" style="position: fixed; width:100%;z-index: 9999;">
<div class="container">
  <a class="navbar-brand" href="#">
    <%= image_tag("icon.jpg", class: "img-responsive d-inline-block align-top icon-size", id: "navbar-logo") %>FilmReview</a>
  <form class="form-inline">
    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
  </form>
	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
	<div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="movies_new">Add a movie</a>
			</li>
      <li class="nav-item">
        <a class="nav-link" href="#">Edit About</a>
			</li>
			<li class="nav-item">
        <a class="nav-link" href="users/sign_out">Signout</a>
			</li>
</nav>
 
<div class="row bgi" style="padding-top:50px;">
<% @movies.each do |movie| %>
<div class="col-sm-4">
	<div class="card text-white bg-dark mb-3" style="width: 18rem; align: center;">
		<div class="card-body">
			<h5 class="card-title"><%= movie.title %></h5>
			<h6 class="card-subtitle mb-2 text-muted"><%= movie.year %></h6>
			<p class="card-text">Category:<%= movie.category %></p>
      <%= link_to "Edit this movie", movie_path(movie), :class => "btn btn-primary" %>
		</div>
	</div>
</div>
<% end %>
</div>

app/views/movies/new.html.erb
<div class="login_align">
    <%= form_with(model: @movie, local: true) do |form| %>
    <p>
        <%= form.label :Title %><br>
        <%= form.text_field :title %>
    </p>
    
    <p>
        <%= form.label :Year %><br>
        <%= form.number_field :year %>
    </p>

    <p>
        <%= form.label :Category %><br>
        <%= form.text_field :category %>
    </p>
    
    <p>
        <%= form.submit %>
    </p>
    
    <% end %>
</div>

app/views/movies/rate.html.erb
<div style="margin-left:20px; margin-top:20px;">
  <div class="card text-center w-100 text-white bg-dark mb-3" style="width: 18rem; align: center;">
		<div class="card-body">
			<h3 class="card-title"><%= @movie.title %></h3>
			<h6 class="card-subtitle mb-2 text-muted"><%= @movie.year %></h6>
			<p class="card-text">Category: <%= @movie.category %></p>
		</div>
	</div>

  <h2>Comments</h2>
  <% @movie.comments.each do |comment| %>
     <div class="card w-100">
      <div class="card-header">
        <%= comment.commenter %>
      </div>
      <div class="card-body">
        <p class="card-text"><%= comment.body %></p>
      </div>
    </div>
  <% end %>
  
  <h2>Add a comment:</h2>
  <%= form_with(model: [ @movie, @movie.comments.build ], local: true) do |form| %>
    <p>
      <%= form.label :commenter %><br>
      <%= form.text_field :commenter %>
    </p>
    <p>
      <%= form.label :body %><br>
      <%= form.text_area :body %>
    </p>
    <p>
      <%= form.submit %>
    </p>
  <% end %>
  
  <%= link_to 'Back', root_path %>
</div>

app/views/movies/show.html.erb
<nav class="navbar navbar-dark bg-dark justify-content-between" style="position: fixed; width:100%;z-index: 9999;">
<div class="container">
  <a class="navbar-brand" href="#">
    <%= image_tag("icon.jpg", class: "img-responsive d-inline-block align-top icon-size", id: "navbar-logo") %>FilmReview</a>
  <form class="form-inline">
    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
  </form>
	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
	<div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="users/sign_in">Admin login</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">About</a>
    </ul>
  </div>
</div>
</nav>
 
<div class="row bgi" style="padding-top:50px;">
<% @movies.each do |movie| %>
<div class="col-sm-4">
	<div class="card text-white bg-dark mb-3" style="width: 18rem; align: center;">
		<div class="card-body">
			<h5 class="card-title"><%= movie.title %></h5>
			<h6 class="card-subtitle mb-2 text-muted"><%= movie.year %></h6>
			<p class="card-text">Category:<%= movie.category %></p>
      <%= link_to "Rate", movies_rate_path(movie), :class => "btn btn-primary" %>
		</div>
	</div>
</div>
<% end %>
</div>

app/views/movies/show_update.html.erb
<div class="login_align">  
  <%= form_with(model: @movie, local: true) do |form| %>
  <p>
    <%= form.label :Title %><br>
    <%= form.text_field :title %>
  </p>
 
  <p>
    <%= form.label :Year %><br>
    <%= form.number_field :year %>
  </p>

  <p>
    <%= form.label :Category %><br>
    <%= form.text_field :category %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
 
  <% end %>
  <%= button_to "Delete", movie_path(@movie), :method => :delete, :class => "btn-danger" %>
  <br>
  <%= link_to 'Back', user_root_path %>
</div>